version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
    privileged: true
    tty: true
    stdin_open: true
